version: "3.8"
services:
  postgres-prisma:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: subaru_dev
    ports:
      - "54321:5432" # host:container
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prisma -d subaru_dev"]
      interval: 5s
      retries: 10
